// Opt-in real-server verification. Creates labelled test records; never mocks API calls.
import assert from 'node:assert/strict';
import { chromium, request, expect } from '@playwright/test';
const email = process.env.MEMBER1_ADMIN_EMAIL;
const password = process.env.MEMBER1_ADMIN_PASSWORD;
if (!email || !password) throw new Error('Supply local demo credentials through environment variables.');
const apiUrl = process.env.MEMBER1_API_URL || 'http://localhost:5295/api/';
const webUrl = process.env.MEMBER1_WEB_URL || 'http://127.0.0.1:5173';
const api = await request.newContext({ baseURL: apiUrl });
const browser = await chromium.launch();
const page = await browser.newPage();
page.setDefaultTimeout(30000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const tag = Date.now().toString();
const name = 'Member1 Browser Integration ' + tag;
try {
  const login = await api.post('auth/login', { data: { email, password } });
  assert.equal(login.status(), 200);
  const session = await login.json();
  const authorization = { Authorization: `Bearer ${session.token}` };
  const specResponse = await api.get('specializations');
  const property = (await specResponse.json()).find(s => s.name === 'Property Law');
  assert.ok(property, 'Expected seeded specialization exists');
  await page.goto(webUrl + '/admin/login');
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Lawyer management' })).toBeVisible();
  await page.getByRole('link', { name: 'Legal services', exact: true }).click();
  const serviceName = 'Property ownership browser test ' + tag;
  await page.getByLabel('Name', { exact: true }).fill(serviceName);
  await page.getByLabel('Description').fill('Labelled integration-test catalog for property ownership disputes.');
  await page.getByLabel('Category').fill('Property Law');
  const savedService = page.waitForResponse(r => r.url().endsWith('/api/legal-services') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  const serviceResponse = await savedService;
  assert.equal(serviceResponse.status(), 201);
  const service = await serviceResponse.json();
  await expect(page.getByRole('heading', { name: serviceName, exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Lawyers', exact: true }).click();
  await page.getByRole('link', { name: 'Add lawyer' }).click();
  for (const [label, value] of [['Full name', name], ['Email', `browser-${tag}@local.example`], ['Phone number', '+94771234567'], ['Qualification', 'Integration test record, not a real practitioner'], ['Years of experience', '9'], ['License number', 'BROWSER-TEST-' + tag], ['Profile description', 'Labelled real-database browser verification fixture.']]) {
    await page.getByLabel(label, { exact: true }).fill(value);
  }
  await page.getByLabel('Specializations (select multiple)').selectOption(String(property.id));
  await page.getByLabel('Legal services (select multiple)').selectOption(String(service.id));
  const savedLawyer = page.waitForResponse(r => r.url().endsWith('/api/lawyer-management') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save lawyer', exact: true }).click();
  const lawyerResponse = await savedLawyer;
  assert.equal(lawyerResponse.status(), 201);
  const lawyer = await lawyerResponse.json();
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  await page.getByLabel('Date', { exact: true }).fill('2030-03-03');
  await page.getByLabel('Start time').fill('09:00:30');
  await page.getByLabel('End time').fill('10:00:45');
  const savedPeriod = page.waitForResponse(r => r.url().endsWith('/availability') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save availability' }).click();
  const periodResponse = await savedPeriod;
  assert.equal(periodResponse.status(), 201);
  const period = await periodResponse.json();
  await expect(page.getByText('2030-03-03 · 09:00–10:00')).toBeVisible();
  await page.getByRole('link', { name: 'Edit profile', exact: true }).click();
  await page.getByLabel('Full name').fill(name + ' Updated');
  await page.getByRole('button', { name: 'Save lawyer', exact: true }).click();
  await expect(page.getByRole('heading', { name: name + ' Updated', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Back to lawyers' }).click();
  await page.getByLabel('Search by name').fill(tag);
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('combobox', { name: /^Specialization/ }).selectOption(String(property.id));
  await page.getByRole('combobox', { name: /^Legal service/ }).selectOption(String(service.id));
  await page.getByLabel('Minimum experience').fill('8');
  await page.getByLabel('Available date').fill('2030-03-03');
  await page.getByRole('combobox', { name: /^Sort/ }).selectOption('experience_desc');
  await expect(page.getByRole('cell', { name: name + ' Updated', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'View / manage' }).click();
  const recommendations = await api.post('lawyer-recommendations', { headers: authorization, data: { requirement: 'I need help with a property ownership dispute.', date: '2030-03-03', limit: 5 } });
  assert.equal(recommendations.status(), 200);
  assert.ok((await recommendations.json()).recommendations.some(r => r.lawyerId === lawyer.lawyerId));
  await page.getByRole('link', { name: 'AI Recommendation' }).click();
  await page.getByRole('button', { name: 'Property dispute', exact: true }).click();
  await page.getByLabel('Preferred date (optional)').fill('2030-03-03');
  const recommendationRequest = page.waitForRequest(r => r.url().endsWith('/api/lawyer-recommendations'));
  await page.getByRole('button', { name: 'Find Suitable Lawyers' }).click();
  assert.match((await recommendationRequest).headers().authorization || '', /^Bearer .+/);
  await expect(page.getByRole('heading', { name: name + ' Updated', exact: true })).toBeVisible();
  for (const width of [390, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Page fits viewport');
  }
  await page.getByRole('article').filter({ has: page.getByRole('heading', { name: name + ' Updated', exact: true }) }).getByRole('link', { name: /View Lawyer/ }).click();
  await page.getByRole('button', { name: 'Deactivate', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(page.getByText('Inactive', { exact: true })).toBeVisible();
  const inactive = await api.get(`lawyers/${lawyer.lawyerId}`, { headers: authorization });
  const stored = await inactive.json();
  assert.equal(stored.status, 'Inactive');
  assert.equal(stored.legalServices[0].id, service.id);
  const updated = await api.put(`lawyers/${lawyer.lawyerId}`, { headers: authorization, data: { ...stored, specializationIds: [property.id], legalServiceIds: [] } });
  assert.equal(updated.status(), 200);
  assert.equal((await api.delete(`lawyers/${lawyer.lawyerId}/availability/${period.availabilityId}`, { headers: authorization })).status(), 204);
  assert.equal((await api.delete(`legal-services/${service.id}`, { headers: authorization })).status(), 204);
  await page.getByRole('link', { name: 'AI Recommendation' }).click();
  await page.getByRole('button', { name: 'Property dispute', exact: true }).click();
  await page.getByLabel('Preferred date (optional)').fill('2030-03-03');
  await page.getByRole('button', { name: 'Find Suitable Lawyers' }).click();
  await expect(page.getByRole('button', { name: 'Find Suitable Lawyers' })).toBeEnabled();
  await expect(page.getByRole('heading', { name: name + ' Updated', exact: true })).toHaveCount(0);
  await page.getByLabel('Describe your legal requirement').fill('I need help with something completely unrelated.');
  await page.getByLabel('Preferred date (optional)').fill('');
  await page.getByRole('button', { name: 'Find Suitable Lawyers' }).click();
  await expect(page.getByText('No suitable active lawyers were found for this requirement.')).toBeVisible();
  assert.deepEqual(errors, []);
  console.log('PASS: real browser login → catalog → lawyer/associations → availability → edit → combined search → view → grounded recommendation → safe deactivation. No API mocks; no browser errors.');
  console.log('Test-created catalog/availability removed; labelled test lawyer remains inactive.');
} finally {
  await browser.close();
  await api.dispose();
}
